# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-14 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='likes_cheese',
            field=models.BooleanField(default=False),
        ),
    ]
